version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-culkmuhu0jms73bo5510-a:5432/pokemon_db
      SPRING_DATASOURCE_USERNAME: root  # Ejemplo: pokemon_user
      SPRING_DATASOURCE_PASSWORD: root  # Ejemplo: pokemon_pass

  db:
    image: mysql:8.0  # Cambia esto si la base de datos es PostgreSQL
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pokemon_db
    ports:
      - "3306:3306"
    volumes:
      - pokemon_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pokemon_mysql_data:
